// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6PK17d-wwIjF4aQGT4seNH9mkIzAP3Q',
    appId: '1:599552293687:web:700b2e9481db209e05b8b2',
    messagingSenderId: '599552293687',
    projectId: 'kidslearning-gohil',
    authDomain: 'kidslearning-gohil.firebaseapp.com',
    storageBucket: 'kidslearning-gohil.appspot.com',
    measurementId: 'G-35MB71TXP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_d5xEHxqHpzKHvhEVcingZKFNmS60OtA',
    appId: '1:599552293687:android:c807c810db373be605b8b2',
    messagingSenderId: '599552293687',
    projectId: 'kidslearning-gohil',
    storageBucket: 'kidslearning-gohil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxXu9LXy72vWKb5NfkOJKGXc-bShYgXI',
    appId: '1:599552293687:ios:313e662fc9ab36e405b8b2',
    messagingSenderId: '599552293687',
    projectId: 'kidslearning-gohil',
    storageBucket: 'kidslearning-gohil.appspot.com',
    iosClientId: '599552293687-v55o86l1h42slb0ch1rsismsha1270vg.apps.googleusercontent.com',
    iosBundleId: 'com.antinna.kidsadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLxXu9LXy72vWKb5NfkOJKGXc-bShYgXI',
    appId: '1:599552293687:ios:313e662fc9ab36e405b8b2',
    messagingSenderId: '599552293687',
    projectId: 'kidslearning-gohil',
    storageBucket: 'kidslearning-gohil.appspot.com',
    iosClientId: '599552293687-v55o86l1h42slb0ch1rsismsha1270vg.apps.googleusercontent.com',
    iosBundleId: 'com.antinna.kidsadmin',
  );
}
